spring:
  application:
    name: order
  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell? characterEncoding=utf-8&useSSL=false
 # jpa:
  #  show-sql: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

env:
  test4
girl:
  name: lili
  age: 18
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: 
